services:

  mqtt-broker:
    build:
      context: ./mqtt

    container_name: mqtt-broker

    ports:
      - "1883:1883"

    restart: unless-stopped

  sensor-generator:
    build:
      context: .
      dockerfile: services/sensor-generator/Dockerfile

    container_name: sensor-generator

    depends_on:
      - mqtt-broker

    # restart: unless-stopped

    volumes:
      - ./datasets:/app/datasets

    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883


  edge-detector:
    build:
      context: .
      dockerfile: services/edge-detector/Dockerfile

    container_name: edge-detector

    depends_on:
      - mqtt-broker

    # restart: unless-stopped

    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883


  data-management:
    build:
      context: .
      dockerfile: services/data-management/Dockerfile

    container_name: data-management

    depends_on:
      - mqtt-broker

    # restart: unless-stopped

    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883
      TARGET_BATCH_COUNT: 10
      MIN_BATCH_INTERVAL: 2.0
      MAX_BATCH_INTERVAL: 30.0
      CLOUD_STORAGE_DIR: /app/cloud_uploads
      LOCAL_CACHE_DIR: /app/local_cache
      CACHE_RETRY_INTERVAL: 30.0
      CACHE_CLEANUP_INTERVAL: 300.0
      CACHE_CLEANUP_MAX_AGE: 3600


  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile

    container_name: orchestrator

    depends_on:
      - mqtt-broker

    # restart: unless-stopped

    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883
      EVAL_WINDOW_SECONDS: 10
      ANOMALY_HIGH_RATIO: 0.5
      ANOMALY_LOW_RATIO: 0.1
      FALLBACK_STREAM_INTERVAL: 0.1
      DIAGNOSIS_ENDPOINT: ""
