services:

  mqtt-broker:
    build:
      context: ./mqtt

    container_name: mqtt-broker

    ports:
      - "1883:1883"

    restart: unless-stopped

  sensor-generator:
    build:
      context: .
      dockerfile: services/sensor-generator/Dockerfile

    container_name: sensor-generator

    depends_on:
      - mqtt-broker

    volumes:
      - ./datasets:/app/datasets

    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883


  edge-detector:
    build:
      context: .
      dockerfile: services/edge-detector/Dockerfile

    container_name: edge-detector

    depends_on:
      - mqtt-broker

    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883
